### ISSUE TITLE
How to connect camera to Raspberry Pi circuit?

### ISSUE THREAD

**Issue by AmlanDwivedy** [androidthings/doorbell#1]
I am ready with Raspberry PI board. I burned android things to Board. As per circuit diagram its really confusing. What will be the complete circuit diagram for Raspberry PI?

**Comment by jdkoren** [comment]
@AmlanDwivedy I'll look into getting a schematic specifically for the Pi. In the meantime, the circuit diagram indicates you need to connect to three pins on the Pi: a 3.3V power, a Ground reference, and a GPIO pin. [DoorbellActivity](https://github.com/androidthings/doorbell/blob/master/app/src/main/java/com/example/androidthings/doorbell/DoorbellActivity.java#L77) expects you to connect to `BCM21` for the GPIO.

Referring to our [pinout diagram](https://developer.android.com/things/hardware/raspberrypi-io.html) for the Raspberry Pi, there are two 3.3V pins (#1 and #17, use either one), several Ground pins, and  `BCM21` is the bottom right (#40).
