### ISSUE TITLE
Unable to preview camera video on raspberry pi 3 using AoT

### ISSUE THREAD

**Issue by EonKid** [androidthings/doorbell#10]
I am using raspberry pi 3 for video streaming .I am unable to preview the camera of raspberry Pi 3 using Android Things .

**Comment by mangini** [comment]
The Raspberry Pi 3 camera HAL pipeline only supports a single stream at a time. You can preview and take snapshots, but you have to close one capture session to start another. See this bug for more information: https://issuetracker.google.com/issues/37130806
