### ISSUE TITLE
Manually grant camera permissions

### ISSUE THREAD

**Issue by riggaroo** [androidthings/doorbell#4]
Hi there, 
I am running this sample, but I had to manually grant the camera permission as I was getting the "No Permission" error on DoorbellActivity. 

`adb shell pm grant com.example.androidthings.doorbell android.permission.CAMERA`

Do you perhaps know why permission was not granted at install time? After granting the permission the sample worked for me.

**Comment by jdkoren** [comment]
You have to reboot the device after installing the app. This is a known issue with Developer Preview 1. From the [release notes](https://developer.android.com/things/preview/releases.html):

> Dangerous permissions requested by apps are not granted until the next device reboot. This includes new app installs and new <uses-permission> elements in existing apps.

**Comment by riggaroo** [comment]
Thanks for the information! 👍
