### ISSUE TITLE
Does AndroidThings support USB camera instead of the Camera Module?

### ISSUE THREAD

**Issue by pandearti** [androidthings/doorbell#7]
Hi, 

I am trying to use a USB camera instead of the camera module. But I am getting below error 

Is it supported by AndroidThings?

03-17 14:00:41.559 5554-5554/net.sourceforge.opencamera I/CameraManagerGlobal: **Connecting to camera service**
03-17 14:00:42.208 5554-5554/net.sourceforge.opencamera E/SensorManager: **sensor or listener is null**
03-17 14:00:42.208 5554-5554/net.sourceforge.opencamera E/SensorManager: sensor or listener is null
03-17 14:00:42.208 5554-5554/net.sourceforge.opencamera W/OrientationEventListener: **Cannot detect sensors. Not enabled**
03-17 14:00:42.222 5554-5644/net.sourceforge.opencamera E/WVMExtractor: **Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found**
.....
.....
03-17 14:00:42.973 154-154/? I/CameraService: CameraService::connect call (PID -1 "net.sourceforge.opencamera", camera ID 0) for HAL version default and Camera API version 1
03-17 14:00:42.973 154-154/? E/CameraService: CameraService::**connect X (PID 5554) rejected (invalid camera ID 0)**
03-17 14:00:42.974 5554-5554/net.sourceforge.opencamera W/CameraBase: An error occurred while connecting to camera 0: Service not available
03-17 14:00:42.975 5554-5554/net.sourceforge.opencamera W/System.err: java.lang.RuntimeException: **Fail to connect to camera service**
03-17 14:00:42.976 5554-5554/net.sourceforge.opencamera W/System.err:     at android.hardware.Camera.<init>(Camera.java:496)
03-17 14:00:42.976 5554-5554/net.sourceforge.opencamera W/System.err:     at android.hardware.Camera.open(Camera.java:345)
03-17 14:00:42.977 5554-5554/net.sourceforge.opencamera W/System.err:     at net.sourceforge.opencamera.CameraController.CameraController1.<init>(CameraController1.java:46)
Thanks

**Comment by mangini** [comment]
No, UVC (USB cameras) is not supported on Android Things at this moment. We support integrated cameras, as these are the most common use cases for IoT devices. If you have a use case for USB camera on your IoT device, could you please chime in on this bug https://code.google.com/p/android/issues/detail?id=230309 ? I'm closing this issue here, since your request is on the platform, not on this sample.
